### ISSUE TITLE
ImportError: No module named 'nets.siamese'

### ISSUE THREAD

**Issue by deimsdeutsch** [forschumi/siamfc-mxnet#2]
Traceback (most recent call last):
  File "run_tracker.py", line 16, in <module>
    import nets.siamese as siamese
ImportError: No module named 'nets.siamese'

**Comment by hf1995** [comment]
Add __init__.py under the nets folder

**Comment by hf1995** [comment]
> Traceback (most recent call last):
> File "run_tracker.py", line 16, in 
> import nets.siamese as siamese
> ImportError: No module named 'nets.siamese'

Maybe you can try adding (__init__.py) under the nets folder.

**Comment by hf1995** [comment]
> Traceback (most recent call last):
> File "run_tracker.py", line 16, in 
> import nets.siamese as siamese
> ImportError: No module named 'nets.siamese'

Maybe you can try adding \_\_init\_\_.py under the nets folder.
